// Mocks generated by Mockito 5.4.4 from annotations
// in caremind/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:caremind/core/errors/result.dart' as _i12;
import 'package:caremind/models/perfil.dart' as _i14;
import 'package:caremind/models/vinculo_familiar.dart' as _i3;
import 'package:caremind/services/location_service.dart' as _i8;
import 'package:caremind/services/notification_service.dart' as _i10;
import 'package:caremind/services/offline_cache_service.dart' as _i11;
import 'package:caremind/services/organizacao_service.dart' as _i4;
import 'package:caremind/services/supabase_service.dart' as _i13;
import 'package:caremind/services/vinculo_familiar_service.dart' as _i9;
import 'package:http/http.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:shared_preferences/shared_preferences.dart' as _i7;
import 'package:supabase/supabase.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFunctionsClient_0 extends _i1.SmartFake
    implements _i2.FunctionsClient {
  _FakeFunctionsClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseStorageClient_1 extends _i1.SmartFake
    implements _i2.SupabaseStorageClient {
  _FakeSupabaseStorageClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeClient_2 extends _i1.SmartFake
    implements _i2.RealtimeClient {
  _FakeRealtimeClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestClient_3 extends _i1.SmartFake
    implements _i2.PostgrestClient {
  _FakePostgrestClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueClient_4 extends _i1.SmartFake implements _i2.GoTrueClient {
  _FakeGoTrueClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQueryBuilder_5 extends _i1.SmartFake
    implements _i2.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQuerySchema_6 extends _i1.SmartFake
    implements _i2.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestFilterBuilder_7<T1> extends _i1.SmartFake
    implements _i2.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeChannel_8 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVinculoFamiliar_9 extends _i1.SmartFake
    implements _i3.VinculoFamiliar {
  _FakeVinculoFamiliar_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrganizacao_10 extends _i1.SmartFake implements _i4.Organizacao {
  _FakeOrganizacao_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseClient_11 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_12 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionResponse_13 extends _i1.SmartFake
    implements _i2.FunctionResponse {
  _FakeFunctionResponse_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i2.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FunctionsClient get functions => (super.noSuchMethod(
        Invocation.getter(#functions),
        returnValue: _FakeFunctionsClient_0(
          this,
          Invocation.getter(#functions),
        ),
      ) as _i2.FunctionsClient);

  @override
  set functions(_i2.FunctionsClient? _functions) => super.noSuchMethod(
        Invocation.setter(
          #functions,
          _functions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.SupabaseStorageClient get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeSupabaseStorageClient_1(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.SupabaseStorageClient);

  @override
  set storage(_i2.SupabaseStorageClient? _storage) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          _storage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.RealtimeClient get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtimeClient_2(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i2.RealtimeClient);

  @override
  set realtime(_i2.RealtimeClient? _realtime) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          _realtime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.PostgrestClient get rest => (super.noSuchMethod(
        Invocation.getter(#rest),
        returnValue: _FakePostgrestClient_3(
          this,
          Invocation.getter(#rest),
        ),
      ) as _i2.PostgrestClient);

  @override
  set rest(_i2.PostgrestClient? _rest) => super.noSuchMethod(
        Invocation.setter(
          #rest,
          _rest,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          headers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.GoTrueClient get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeGoTrueClient_4(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i2.GoTrueClient);

  @override
  _i2.SupabaseQueryBuilder from(String? table) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [table],
        ),
        returnValue: _FakeSupabaseQueryBuilder_5(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
      ) as _i2.SupabaseQueryBuilder);

  @override
  _i2.SupabaseQuerySchema schema(String? schema) => (super.noSuchMethod(
        Invocation.method(
          #schema,
          [schema],
        ),
        returnValue: _FakeSupabaseQuerySchema_6(
          this,
          Invocation.method(
            #schema,
            [schema],
          ),
        ),
      ) as _i2.SupabaseQuerySchema);

  @override
  _i2.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rpc,
          [fn],
          {
            #params: params,
            #get: get,
          },
        ),
        returnValue: _FakePostgrestFilterBuilder_7<T>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #get: get,
            },
          ),
        ),
      ) as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.RealtimeChannel channel(
    String? name, {
    _i2.RealtimeChannelConfig? opts = const _i2.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #channel,
          [name],
          {#opts: opts},
        ),
        returnValue: _FakeRealtimeChannel_8(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
      ) as _i2.RealtimeChannel);

  @override
  List<_i2.RealtimeChannel> getChannels() => (super.noSuchMethod(
        Invocation.method(
          #getChannels,
          [],
        ),
        returnValue: <_i2.RealtimeChannel>[],
      ) as List<_i2.RealtimeChannel>);

  @override
  _i5.Future<String> removeChannel(_i2.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeChannel,
          [channel],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<String>> removeAllChannels() => (super.noSuchMethod(
        Invocation.method(
          #removeAllChannels,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i7.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i5.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i8.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, double>?> getCurrentLocation(
          {Duration? timeout = const Duration(seconds: 10)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i5.Future<Map<String, double>?>.value(),
      ) as _i5.Future<Map<String, double>?>);

  @override
  _i5.Future<bool> isLocationAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isLocationAvailable,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String> getLocationStatusMessage() => (super.noSuchMethod(
        Invocation.method(
          #getLocationStatusMessage,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getLocationStatusMessage,
            [],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [VinculoFamiliarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVinculoFamiliarService extends _i1.Mock
    implements _i9.VinculoFamiliarService {
  MockVinculoFamiliarService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.VinculoFamiliar>> getVinculosByFamiliar(
          String? familiarId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVinculosByFamiliar,
          [familiarId],
        ),
        returnValue: _i5.Future<List<_i3.VinculoFamiliar>>.value(
            <_i3.VinculoFamiliar>[]),
      ) as _i5.Future<List<_i3.VinculoFamiliar>>);

  @override
  _i5.Future<List<_i3.VinculoFamiliar>> getVinculosByIdoso(String? idosoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVinculosByIdoso,
          [idosoId],
        ),
        returnValue: _i5.Future<List<_i3.VinculoFamiliar>>.value(
            <_i3.VinculoFamiliar>[]),
      ) as _i5.Future<List<_i3.VinculoFamiliar>>);

  @override
  _i5.Future<_i3.VinculoFamiliar> createVinculo({
    required String? idIdoso,
    required String? idFamiliar,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVinculo,
          [],
          {
            #idIdoso: idIdoso,
            #idFamiliar: idFamiliar,
          },
        ),
        returnValue:
            _i5.Future<_i3.VinculoFamiliar>.value(_FakeVinculoFamiliar_9(
          this,
          Invocation.method(
            #createVinculo,
            [],
            {
              #idIdoso: idIdoso,
              #idFamiliar: idFamiliar,
            },
          ),
        )),
      ) as _i5.Future<_i3.VinculoFamiliar>);

  @override
  _i5.Future<void> deleteVinculo({
    required String? idIdoso,
    required String? idFamiliar,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVinculo,
          [],
          {
            #idIdoso: idIdoso,
            #idFamiliar: idFamiliar,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> existsVinculo({
    required String? idIdoso,
    required String? idFamiliar,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #existsVinculo,
          [],
          {
            #idIdoso: idIdoso,
            #idFamiliar: idFamiliar,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i10.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [OfflineCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineCacheService extends _i1.Mock
    implements _i11.OfflineCacheService {
  MockOfflineCacheService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [OrganizacaoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrganizacaoService extends _i1.Mock
    implements _i4.OrganizacaoService {
  MockOrganizacaoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i12.Result<_i4.Organizacao>> criarOrganizacao({
    required String? nome,
    String? cnpj,
    String? telefone,
    String? email,
    Map<String, dynamic>? endereco,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #criarOrganizacao,
          [],
          {
            #nome: nome,
            #cnpj: cnpj,
            #telefone: telefone,
            #email: email,
            #endereco: endereco,
          },
        ),
        returnValue: _i5.Future<_i12.Result<_i4.Organizacao>>.value(
            _i6.dummyValue<_i12.Result<_i4.Organizacao>>(
          this,
          Invocation.method(
            #criarOrganizacao,
            [],
            {
              #nome: nome,
              #cnpj: cnpj,
              #telefone: telefone,
              #email: email,
              #endereco: endereco,
            },
          ),
        )),
      ) as _i5.Future<_i12.Result<_i4.Organizacao>>);

  @override
  _i5.Future<List<_i4.Organizacao>> listarOrganizacoes() => (super.noSuchMethod(
        Invocation.method(
          #listarOrganizacoes,
          [],
        ),
        returnValue:
            _i5.Future<List<_i4.Organizacao>>.value(<_i4.Organizacao>[]),
      ) as _i5.Future<List<_i4.Organizacao>>);

  @override
  _i5.Future<_i4.Organizacao> obterOrganizacao(String? organizacaoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #obterOrganizacao,
          [organizacaoId],
        ),
        returnValue: _i5.Future<_i4.Organizacao>.value(_FakeOrganizacao_10(
          this,
          Invocation.method(
            #obterOrganizacao,
            [organizacaoId],
          ),
        )),
      ) as _i5.Future<_i4.Organizacao>);

  @override
  _i5.Future<_i4.Organizacao> atualizarOrganizacao(
    String? organizacaoId, {
    String? nome,
    String? cnpj,
    String? telefone,
    String? email,
    Map<String, dynamic>? endereco,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #atualizarOrganizacao,
          [organizacaoId],
          {
            #nome: nome,
            #cnpj: cnpj,
            #telefone: telefone,
            #email: email,
            #endereco: endereco,
          },
        ),
        returnValue: _i5.Future<_i4.Organizacao>.value(_FakeOrganizacao_10(
          this,
          Invocation.method(
            #atualizarOrganizacao,
            [organizacaoId],
            {
              #nome: nome,
              #cnpj: cnpj,
              #telefone: telefone,
              #email: email,
              #endereco: endereco,
            },
          ),
        )),
      ) as _i5.Future<_i4.Organizacao>);

  @override
  _i5.Future<String?> obterRoleOrganizacao(String? organizacaoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #obterRoleOrganizacao,
          [organizacaoId],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> isMembroOrganizacao(String? organizacaoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #isMembroOrganizacao,
          [organizacaoId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isAdmin(String? organizacaoId) => (super.noSuchMethod(
        Invocation.method(
          #isAdmin,
          [organizacaoId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [SupabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseService extends _i1.Mock implements _i13.SupabaseService {
  MockSupabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeSupabaseClient_11(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.SupabaseClient);

  @override
  _i5.Stream<_i2.AuthState> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i5.Stream<_i2.AuthState>.empty(),
      ) as _i5.Stream<_i2.AuthState>);

  @override
  _i5.Future<_i2.AuthResponse> signUp({
    required String? email,
    required String? password,
    required String? nome,
    required String? tipo,
    String? telefone,
    bool? lgpdConsent = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
            #nome: nome,
            #tipo: tipo,
            #telefone: telefone,
            #lgpdConsent: lgpdConsent,
          },
        ),
        returnValue: _i5.Future<_i2.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #password: password,
              #nome: nome,
              #tipo: tipo,
              #telefone: telefone,
              #lgpdConsent: lgpdConsent,
            },
          ),
        )),
      ) as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i2.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signIn,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<bool> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> gerarCodigoVinculacao() => (super.noSuchMethod(
        Invocation.method(
          #gerarCodigoVinculacao,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #gerarCodigoVinculacao,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<Map<String, dynamic>> vincularPorCodigo(String? codigo) =>
      (super.noSuchMethod(
        Invocation.method(
          #vincularPorCodigo,
          [codigo],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> criarEVincularIdoso({
    required String? nome,
    required String? email,
    required String? senha,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #criarEVincularIdoso,
          [],
          {
            #nome: nome,
            #email: email,
            #senha: senha,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> atualizarIdoso({
    required String? idosoId,
    required String? nome,
    String? telefone,
    String? dataNascimento,
    String? fotoUsuario,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #atualizarIdoso,
          [],
          {
            #idosoId: idosoId,
            #nome: nome,
            #telefone: telefone,
            #dataNascimento: dataNascimento,
            #fotoUsuario: fotoUsuario,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i14.Perfil?> getProfile(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [userId],
        ),
        returnValue: _i5.Future<_i14.Perfil?>.value(),
      ) as _i5.Future<_i14.Perfil?>);

  @override
  _i5.Future<void> updateProfile({
    required String? userId,
    String? nome,
    String? tipo,
    String? codigoVinculacao,
    String? fotoUsuario,
    DateTime? codigoVinculacaoExpiraEm,
    String? telefone,
    String? timezone,
    bool? dataSharingConsent,
    DateTime? termsAcceptedAt,
    bool? notificacoesCompromissos,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #userId: userId,
            #nome: nome,
            #tipo: tipo,
            #codigoVinculacao: codigoVinculacao,
            #fotoUsuario: fotoUsuario,
            #codigoVinculacaoExpiraEm: codigoVinculacaoExpiraEm,
            #telefone: telefone,
            #timezone: timezone,
            #dataSharingConsent: dataSharingConsent,
            #termsAcceptedAt: termsAcceptedAt,
            #notificacoesCompromissos: notificacoesCompromissos,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i14.Perfil>> getIdososVinculados(String? familiarId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdososVinculados,
          [familiarId],
        ),
        returnValue: _i5.Future<List<_i14.Perfil>>.value(<_i14.Perfil>[]),
      ) as _i5.Future<List<_i14.Perfil>>);

  @override
  _i5.Future<void> desvincularIdoso(String? idosoId) => (super.noSuchMethod(
        Invocation.method(
          #desvincularIdoso,
          [idosoId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getCuidadorPrincipal(String? idosoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCuidadorPrincipal,
          [idosoId],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> removerIdoso(String? idosoId) => (super.noSuchMethod(
        Invocation.method(
          #removerIdoso,
          [idosoId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [FunctionsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFunctionsClient extends _i1.Mock implements _i2.FunctionsClient {
  MockFunctionsClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  void setAuth(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAuth,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.FunctionResponse> invoke(
    String? functionName, {
    Map<String, String>? headers,
    Object? body,
    Iterable<_i15.MultipartFile>? files,
    Map<String, dynamic>? queryParameters,
    _i2.HttpMethod? method = _i2.HttpMethod.post,
    String? region,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [functionName],
          {
            #headers: headers,
            #body: body,
            #files: files,
            #queryParameters: queryParameters,
            #method: method,
            #region: region,
          },
        ),
        returnValue:
            _i5.Future<_i2.FunctionResponse>.value(_FakeFunctionResponse_13(
          this,
          Invocation.method(
            #invoke,
            [functionName],
            {
              #headers: headers,
              #body: body,
              #files: files,
              #queryParameters: queryParameters,
              #method: method,
              #region: region,
            },
          ),
        )),
      ) as _i5.Future<_i2.FunctionResponse>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
